using System;
using System.Collections.Generic;

namespace BBT.Aether.Events;

/// <summary>
/// Generic CloudEvents 1.0 compliant envelope for distributed events with strongly-typed data.
/// This envelope is automatically created by the EventBus when publishing events.
/// The Type contains the EventName from EventNameAttribute for handler resolution.
/// The Topic contains the full routing topic name generated by TopicNameStrategy.
/// The Source is populated from AetherEventBusOptions.DefaultSource.
/// Used by event handlers for type-safe access to event data and metadata.
/// </summary>
/// <typeparam name="TData">The type of the event data</typeparam>
public class CloudEventEnvelope<TData>
{
    /// <summary>
    /// CloudEvents specification version. Default: "1.0"
    /// </summary>
    public string SpecVersion { get; init; } = "1.0";

    /// <summary>
    /// Unique identifier for the event. Auto-generated as GUID if not provided.
    /// </summary>
    public string Id { get; init; } = Guid.NewGuid().ToString("N");

    /// <summary>
    /// Event type identifier. Contains the EventName from EventNameAttribute.
    /// Used for handler resolution via the distributed event invoker registry.
    /// Format: "EventName" (e.g., "OrderCreated", "UserRegistered")
    /// </summary>
    public string Type { get; init; } = default!;

    /// <summary>
    /// Topic name for routing the event to the message broker.
    /// Generated by TopicNameStrategy from EventNameAttribute.
    /// Format: "EventName.vX" or "{environment}.domain.EventName.vX" if environment prefix is enabled.
    /// CloudEvent extension attribute.
    /// </summary>
    public string? Topic { get; init; }

    /// <summary>
    /// Source identifier. Automatically populated from AetherEventBusOptions.DefaultSource.
    /// Format: "urn:vnext:{service}"
    /// </summary>
    public string? Source { get; init; }

    /// <summary>
    /// Subject identifier (e.g., aggregate ID). Optional, provided via PublishAsync subject parameter.
    /// </summary>
    public string? Subject { get; init; }

    /// <summary>
    /// Event timestamp. Default: DateTimeOffset.UtcNow
    /// </summary>
    public DateTimeOffset Time { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Content type of the data. Default: "application/json"
    /// </summary>
    public string? DataContentType { get; init; } = "application/json";
    
    /// <summary>
    /// URI reference to the schema that the data adheres to.
    /// </summary>
    public string? DataSchema { get; init; }

    /// <summary>
    /// Event version from EventNameAttribute. Used for handler routing and versioning.
    /// CloudEvent extension attribute.
    /// </summary>
    public int? Version { get; init; }

    /// <summary>
    /// The strongly-typed event payload data.
    /// </summary>
    public TData Data { get; init; } = default!;
    
    /// <summary>
    /// Logical runtime key used to resolve DB schema, runtime config etc.
    /// Example: "retail-core", "corporate-loan"
    /// </summary>
    public string? RuntimeKey { get; init; }
    
    /// <summary>
    /// Database schema name for multi-schema scenarios.
    /// CloudEvent extension attribute.
    /// </summary>
    public string? Schema { get; init; }
    
    /// <summary>
    /// Tenant identifier for multi-tenant scenarios.
    /// CloudEvent extension attribute.
    /// </summary>
    public string? TenantId { get; init; }
    
    /// <summary>
    /// CloudEvent extension attributes for custom metadata.
    /// Allows storing additional context data that doesn't fit into standard CloudEvent fields.
    /// </summary>
    public Dictionary<string, object>? Extensions { get; init; }
}

/// <summary>
/// Non-generic CloudEvents 1.0 compliant envelope for distributed events.
/// Convenience alias for CloudEventEnvelope&lt;object&gt;.
/// Use this when the event data type is not known at compile time.
/// </summary>
public class CloudEventEnvelope : CloudEventEnvelope<object>
{
}

